<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
<title>LibSylph: Sylph::Core::Exception Class Reference</title>
<link href="tabs.css" rel="stylesheet" type="text/css">
<link href="doxygen.css" rel="stylesheet" type="text/css">
</head><body>
<!-- Generated by Doxygen 1.5.8 -->
<div class="navigation" id="top">
  <div class="tabs">
    <ul>
      <li><a href="index.html"><span>Main&nbsp;Page</span></a></li>
      <li><a href="namespaces.html"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.html"><span>Classes</span></a></li>
      <li><a href="files.html"><span>Files</span></a></li>
    </ul>
  </div>
  <div class="tabs">
    <ul>
      <li><a href="annotated.html"><span>Class&nbsp;List</span></a></li>
      <li><a href="hierarchy.html"><span>Class&nbsp;Hierarchy</span></a></li>
      <li><a href="functions.html"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
  <div class="navpath"><a class="el" href="namespace_sylph.html">Sylph</a>::<a class="el" href="namespace_sylph_1_1_core.html">Core</a>::<a class="el" href="class_sylph_1_1_core_1_1_exception.html">Exception</a>
  </div>
</div>
<div class="contents">
<h1>Sylph::Core::Exception Class Reference</h1><!-- doxytag: class="Sylph::Core::Exception" --><!-- doxytag: inherits="Sylph::Core::Object,std::exception" -->This class provides a ready-to-use interface for exception handling.  
<a href="#_details">More...</a>
<p>
<code>#include &lt;<a class="el" href="_exception_8h-source.html">Sylph/Core/Exception.h</a>&gt;</code>
<p>
Inherits <a class="el" href="class_sylph_1_1_core_1_1_object.html">Sylph::Core::Object</a>, and std::exception.
<p>

<p>
<a href="class_sylph_1_1_core_1_1_exception-members.html">List of all members.</a><table border="0" cellpadding="0" cellspacing="0">
<tr><td></td></tr>
<tr><td colspan="2"><br><h2>Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" nowrap align="right" valign="top">&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_sylph_1_1_core_1_1_exception.html#f3df465262dc2dd2c2b655c49dcb8178">Exception</a> (string_t &amp;n, string_t &amp;r=&quot;&quot;, string_t &amp;f=&quot;unknown&quot;, const unsigned int l=0)  throw ()</td></tr>

<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Creates a new <a class="el" href="class_sylph_1_1_core_1_1_exception.html" title="This class provides a ready-to-use interface for exception handling.">Exception</a>.  <a href="#f3df465262dc2dd2c2b655c49dcb8178"></a><br></td></tr>
<tr><td class="memItemLeft" nowrap align="right" valign="top"><a class="anchor" name="563ac89dcc4f7a4c7471bd290c28e9d7"></a><!-- doxytag: member="Sylph::Core::Exception::~Exception" ref="563ac89dcc4f7a4c7471bd290c28e9d7" args="()" -->
&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_sylph_1_1_core_1_1_exception.html#563ac89dcc4f7a4c7471bd290c28e9d7">~Exception</a> ()  throw ()</td></tr>

<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Default destructor. <br></td></tr>
<tr><td class="memItemLeft" nowrap align="right" valign="top">const char *&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_sylph_1_1_core_1_1_exception.html#97e8e53edf192523669bddc3378b0f7f">what</a> () const   throw ()</td></tr>

<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Returns the reason why this <a class="el" href="class_sylph_1_1_core_1_1_exception.html" title="This class provides a ready-to-use interface for exception handling.">Exception</a> was thrown, i.e. the second parameter to <code>sthrow()</code>.  <a href="#97e8e53edf192523669bddc3378b0f7f"></a><br></td></tr>
<tr><td class="memItemLeft" nowrap align="right" valign="top">string_t &amp;&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_sylph_1_1_core_1_1_exception.html#d922d06c02438ff944a6f609017c14e1">name</a> () const   throw ()</td></tr>

<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Returns the name of this <a class="el" href="class_sylph_1_1_core_1_1_exception.html" title="This class provides a ready-to-use interface for exception handling.">Exception</a>.  <a href="#d922d06c02438ff944a6f609017c14e1"></a><br></td></tr>
<tr><td colspan="2"><br><h2>Public Attributes</h2></td></tr>
<tr><td class="memItemLeft" nowrap align="right" valign="top"><a class="anchor" name="cec07e82e18d91dca588083538a0fd78"></a><!-- doxytag: member="Sylph::Core::Exception::file" ref="cec07e82e18d91dca588083538a0fd78" args="" -->
const string_t&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_sylph_1_1_core_1_1_exception.html#cec07e82e18d91dca588083538a0fd78">file</a></td></tr>

<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Do not use. <br></td></tr>
<tr><td class="memItemLeft" nowrap align="right" valign="top"><a class="anchor" name="e3d5592e999bdda42fec64ab44cbc8fd"></a><!-- doxytag: member="Sylph::Core::Exception::line" ref="e3d5592e999bdda42fec64ab44cbc8fd" args="" -->
const unsigned int&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_sylph_1_1_core_1_1_exception.html#e3d5592e999bdda42fec64ab44cbc8fd">line</a></td></tr>

<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Do not use. <br></td></tr>
</table>
<hr><a name="_details"></a><h2>Detailed Description</h2>
This class provides a ready-to-use interface for exception handling. 
<p>
Unlike most exception classes, you should not extend this class. Instead, use the <code>sthrow</code> keyword to throw an <a class="el" href="class_sylph_1_1_core_1_1_exception.html" title="This class provides a ready-to-use interface for exception handling.">Exception</a>, like this: <pre>void Foo::foobar(const Bar &amp; bar) {
     if(bar.myint &lt; 0)
        sthrow(IllegalArgumentException,
           "Cannot foobar() when Bar::myint &lt; 0");
     else {
       // ...
     }
 }</pre> <code>sthrow</code> will ensure that a <a class="el" href="class_sylph_1_1_core_1_1_exception.html" title="This class provides a ready-to-use interface for exception handling.">Sylph::Core::Exception</a> is thrown, even when it is not in scope. <code>sthrow</code> also adds certain debug information, i.e. file and line numbers, if compilation with the debug flag (<code>-DSYLPH_DEBUG</code>) is enabled. <p>
Note that in the example above, no class named <code>IllegalArgumentException</code> actually exists. Instead, the name of the <a class="el" href="class_sylph_1_1_core_1_1_exception.html" title="This class provides a ready-to-use interface for exception handling.">Exception</a> is stored in a String inside this class. Therefore, there are no fixed <a class="el" href="class_sylph_1_1_core_1_1_exception.html" title="This class provides a ready-to-use interface for exception handling.">Exception</a> types, however, the following are recommended: <ul>
<li>
<code>ArrayException</code> -- A generic <a class="el" href="class_sylph_1_1_core_1_1_exception.html" title="This class provides a ready-to-use interface for exception handling.">Exception</a> thrown when trying to access an item outside the bounds of an <code><a class="el" href="class_sylph_1_1_core_1_1_array.html" title="Array provides a safe array.">Array</a></code>. </li>
<li>
<code>FileException</code> -- A generic <a class="el" href="class_sylph_1_1_core_1_1_exception.html" title="This class provides a ready-to-use interface for exception handling.">Exception</a> thrown when a file is is not of the supported type, e.g. a directory instead of a regular file. When writing or reading from a file, throw an <code>IOException</code> instead  </li>
<li>
<code>IllegalArgumentException</code> -- Similar to the <code>IllegalStateException</code>, however, this <a class="el" href="class_sylph_1_1_core_1_1_exception.html" title="This class provides a ready-to-use interface for exception handling.">Exception</a> is meant especially for arguments that do not conform to a given set of criteria, where an <code>IllegalStateException</code> can also be thrown when certain conditions, apart from arguments, are not met. </li>
<li>
<code>IllegalStateException</code> -- The object on which to perform the action is not in the right state, i.e. a variable does not have the right value to perform te action. </li>
<li>
<code>IOException</code> -- This <a class="el" href="class_sylph_1_1_core_1_1_exception.html" title="This class provides a ready-to-use interface for exception handling.">Exception</a> is thrown whenever an I/O operation, such as a read or a write to a file, or establishing a network connection, failed.  </li>
<li>
<code>NullPointerException</code> -- This <a class="el" href="class_sylph_1_1_core_1_1_exception.html" title="This class provides a ready-to-use interface for exception handling.">Exception</a> is thrown by the <code>check_nullptr()</code> macro. Like it name says, it denotes the dereference of a null (0) pointer.  </li>
<li>
<code>SerialisationException</code> -- This <a class="el" href="class_sylph_1_1_core_1_1_exception.html" title="This class provides a ready-to-use interface for exception handling.">Exception</a> is thrown by <code>Serializer</code> s and <code>Deserializer</code> s when the type of the serialised object and the destination don't match, or when the object could not be serialised due to another <a class="el" href="class_sylph_1_1_core_1_1_exception.html" title="This class provides a ready-to-use interface for exception handling.">Exception</a>, such as an I/O error.  </li>
<li>
<code>TodoException</code> -- similar to the UnsupportedOperationException, however, this <a class="el" href="class_sylph_1_1_core_1_1_exception.html" title="This class provides a ready-to-use interface for exception handling.">Exception</a> type denotes that the operation itself is supported, but not yet implemented by the programmer.  </li>
<li>
<code>UnsupportedOperationException</code> -- this <a class="el" href="class_sylph_1_1_core_1_1_exception.html" title="This class provides a ready-to-use interface for exception handling.">Exception</a> is usually thrown by classes that are derived from classes with only pure virtual fucntions. This exception denotes that a particular action just doesn't make sense in the case of the implementing class. </li>
</ul>
<hr><h2>Constructor &amp; Destructor Documentation</h2>
<a class="anchor" name="f3df465262dc2dd2c2b655c49dcb8178"></a><!-- doxytag: member="Sylph::Core::Exception::Exception" ref="f3df465262dc2dd2c2b655c49dcb8178" args="(string_t &amp;n, string_t &amp;r=&quot;&quot;, string_t &amp;f=&quot;unknown&quot;, const unsigned int l=0)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">Sylph::Core::Exception::Exception           </td>
          <td>(</td>
          <td class="paramtype">string_t &amp;&nbsp;</td>
          <td class="paramname"> <em>n</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">string_t &amp;&nbsp;</td>
          <td class="paramname"> <em>r</em> = <code>&quot;&quot;</code>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">string_t &amp;&nbsp;</td>
          <td class="paramname"> <em>f</em> = <code>&quot;unknown&quot;</code>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const unsigned int&nbsp;</td>
          <td class="paramname"> <em>l</em> = <code>0</code></td><td>&nbsp;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td><td>  throw ()<code> [inline]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>
Creates a new <a class="el" href="class_sylph_1_1_core_1_1_exception.html" title="This class provides a ready-to-use interface for exception handling.">Exception</a>. 
<p>
You should not use this directly, instead, use <code>sthrow()</code> 
</div>
</div><p>
<hr><h2>Member Function Documentation</h2>
<a class="anchor" name="d922d06c02438ff944a6f609017c14e1"></a><!-- doxytag: member="Sylph::Core::Exception::name" ref="d922d06c02438ff944a6f609017c14e1" args="() const " -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">string_t&amp; Sylph::Core::Exception::name           </td>
          <td>(</td>
          <td class="paramname">          </td>
          <td>&nbsp;)&nbsp;</td>
          <td> const  throw ()<code> [inline]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>
Returns the name of this <a class="el" href="class_sylph_1_1_core_1_1_exception.html" title="This class provides a ready-to-use interface for exception handling.">Exception</a>. 
<p>
The name denotes the unique type of this <a class="el" href="class_sylph_1_1_core_1_1_exception.html" title="This class provides a ready-to-use interface for exception handling.">Exception</a>, and is used instead of subclassing. It is the first parameter to <code>sthrow()</code> <dl class="return" compact><dt><b>Returns:</b></dt><dd>The name of this <a class="el" href="class_sylph_1_1_core_1_1_exception.html" title="This class provides a ready-to-use interface for exception handling.">Exception</a>, as defined by <code>sthrow()</code> </dd></dl>

</div>
</div><p>
<a class="anchor" name="97e8e53edf192523669bddc3378b0f7f"></a><!-- doxytag: member="Sylph::Core::Exception::what" ref="97e8e53edf192523669bddc3378b0f7f" args="() const " -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">const char* Sylph::Core::Exception::what           </td>
          <td>(</td>
          <td class="paramname">          </td>
          <td>&nbsp;)&nbsp;</td>
          <td> const  throw ()<code> [inline]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>
Returns the reason why this <a class="el" href="class_sylph_1_1_core_1_1_exception.html" title="This class provides a ready-to-use interface for exception handling.">Exception</a> was thrown, i.e. the second parameter to <code>sthrow()</code>. 
<p>
<dl class="return" compact><dt><b>Returns:</b></dt><dd>The reason why this <a class="el" href="class_sylph_1_1_core_1_1_exception.html" title="This class provides a ready-to-use interface for exception handling.">Exception</a> was thrown. </dd></dl>

</div>
</div><p>
<hr>The documentation for this class was generated from the following file:<ul>
<li>Sylph/Core/<a class="el" href="_exception_8h-source.html">Exception.h</a></ul>
</div>
<hr size="1"><address style="text-align: right;"><small>Generated on Sat Mar 21 15:05:26 2009 for LibSylph by&nbsp;
<a href="http://www.doxygen.org/index.html">
<img src="doxygen.png" alt="doxygen" align="middle" border="0"></a> 1.5.8 </small></address>
</body>
</html>
